on:
  issues:
    types: [opened]

permissions:
  issues: write
  contents: read

jobs:
  add-guidelines:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Comment if no label was added
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          LABELS='${{ toJson(github.event.issue.labels) }}'

          if [ "$LABELS" = "[]" ]; then
            gh issue comment ${{ github.event.issue.number }} --body-file ./guidelines.md
          fi
